language: ruby

before_install:
  - gem install bundler

script:
  — bundle exec rake db:create
  — bundle exec rake db:migrate
  — bundle exec rspec

after_script:
  - bundle exec rake coveralls:push
