---
development:
  cloud_name: dgbmeqmyf
  api_key: '767613739292841'
  api_secret: M3ohHo1FYekv_8yDlHtg9OvKAK4
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dgbmeqmyf
  api_key: '767613739292841'
  api_secret: M3ohHo1FYekv_8yDlHtg9OvKAK4
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dgbmeqmyf
  api_key: '767613739292841'
  api_secret: M3ohHo1FYekv_8yDlHtg9OvKAK4
  enhance_image_tag: true
  static_file_support: false
